// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhsXO69wF4PSpnrMevQZhEmaCfYCi2NMU',
    appId: '1:338191781683:web:bf809aeb6b9689a4023846',
    messagingSenderId: '338191781683',
    projectId: 'restricter-connector',
    authDomain: 'restricter-connector.firebaseapp.com',
    storageBucket: 'restricter-connector.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbMs53bAK1M0ez7JBnfODOdD8kP-ax3nw',
    appId: '1:338191781683:android:2913fef37439c967023846',
    messagingSenderId: '338191781683',
    projectId: 'restricter-connector',
    storageBucket: 'restricter-connector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0om1keUftTmQBXzD5jxWXHa_aUiojHmk',
    appId: '1:338191781683:ios:e0defdbe867b826a023846',
    messagingSenderId: '338191781683',
    projectId: 'restricter-connector',
    storageBucket: 'restricter-connector.firebasestorage.app',
    iosBundleId: 'com.example.restricter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0om1keUftTmQBXzD5jxWXHa_aUiojHmk',
    appId: '1:338191781683:ios:e0defdbe867b826a023846',
    messagingSenderId: '338191781683',
    projectId: 'restricter-connector',
    storageBucket: 'restricter-connector.firebasestorage.app',
    iosBundleId: 'com.example.restricter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhsXO69wF4PSpnrMevQZhEmaCfYCi2NMU',
    appId: '1:338191781683:web:dd08e6f45242659a023846',
    messagingSenderId: '338191781683',
    projectId: 'restricter-connector',
    authDomain: 'restricter-connector.firebaseapp.com',
    storageBucket: 'restricter-connector.firebasestorage.app',
  );
}
